[[language]]
name = "python"
auto-format = true
language-servers = ["pyright", "ruff"]

[language.formatter]
command = "ruff"
args = ["format", "-"]

[language.indent]
unit = "\t"
tab-width = 3

[[language]]
name = "yuck"
scope = "source.yuck"
injection-regex = "yuck"
file-types = ["yuck"]
language-servers = ["yuckls"]

[language.indent]
unit = "\t"
tab-width = 5

[[language]]
name = "latex"
scope = "source.tex"
injection-regex = "tex"
file-types = ["tex"]
roots = []
comment-token = "%"
language-servers = ["texlab"]
auto-format = false

[language.formatter]
command = "prettier"
args = [
  "--plugin=/usr/lib/node_modules/prettier-plugin-latex/dist/prettier-plugin-latex.js",
  "%{buffer_name}",
]

[language.indent]
unit = "\t"
tab-width = 5

[[language]]
name = "haskell"
scope = "source.hs"
file-types = ["hs"]
auto-format = true
indent = { unit = "\t", tab-width = 5 }

[[language]]
name = "toml"
auto-format = true

[language.formatter]
command = "taplo"
args = ["fmt", "-"]

[language.indent]
unit = "\t"
tab-width = 5

[[language]]
name = "qml"
auto-format = false
roots = ["shell.qml", "qmldir"]

[language.formatter]
command = "qmlformat"
args = ["%{buffer_name}"]

[language.indent]
unit = "\t"
tab-width = 5

[[language]]
name = "zig"
auto-format = true

[language.indent]
unit = "\t"
tab-width = 5

[[language]]
name = "typescript"
file-types = ["ts"]

[language.indent]
unit = "\t"
tab-width = 5

[[language]]
name = "typst"
formatter.command = "typstyle"
auto-format = true

[language-server]
yuckls = { command = "dotnet", args = [
  "/home/gitrepos/yuckls/YuckLS/dist/YuckLS.dll",
] } #must be where you cloned this repo to
#yuckls = {command = "yuckls } #if installed from aur

[language-server.texlab]
command = "texlab"
config = { texlab = { build = { onSave = true } } }
indent = { tab-width = 5, unit = "\t" }

[language-server.qmlls]
args = ["-E"]
command = "qmlls"

[language-server.pyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]
